#!/usr/bin/python3

# Check if the PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
	echo "Error: PYFILE environment variable not set. Please export the filename of the Python script."
	exit 1
fi

# Check if the file specified in the PYFILE variable exists
if [ ! -f "$PYFILE" ]; then
	echo "Error: The file '$PYFILE' does not exist."
	exit 1
fi

# Execute the Python script
python3 "$PYFILE"

